# Copyright 2022 The Magma Authors.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: LTE integ test bazel

on:
  workflow_dispatch: null
  workflow_run:
    workflows:
      - build-all
    branches:
      - master
    types:
      - completed

env:
  CACHE_KEY_MAGMA_DEV: magma-dev-vm
  CACHE_KEY_MAGMA_TEST: magma-test-vm
  REMOTE_DOWNLOAD_OPTIMIZATION: false

jobs:
  lte-integ-test-bazel:
    if: github.repository_owner == 'magma' || github.event_name == 'workflow_dispatch'
    runs-on: macos-12
    env:
      SHA: ${{ github.event.workflow_run.head_commit.id || github.sha }}
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2
        with:
          ref: ${{ env.SHA }}
      - name: Cache magma-dev-box
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # pin@v3
        with:
          path: ~/.vagrant.d/boxes/magmacore-VAGRANTSLASH-magma_dev
          key: vagrant-box-magma-dev-v1.2.20220801
      - name: Cache magma-test-box
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # pin@v3
        with:
          path: ~/.vagrant.d/boxes/magmacore-VAGRANTSLASH-magma_test
          key: vagrant-box-magma-test
      - name: Cache magma-trfserver-box
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # pin@v3
        with:
          path: ~/.vagrant.d/boxes/magmacore-VAGRANTSLASH-magma_trfserver
          key: vagrant-box-magma-trfserver-v20220722
      - name: Log in to vagrant cloud
        run: |
          if [[ -n "${{ secrets.VAGRANT_TOKEN }}" ]]
          then
            echo "Logging in to vagrant cloud to mitigate rate limiting."
            vagrant cloud auth login --token "${{ secrets.VAGRANT_TOKEN }}"
          else
            echo "Vagrant cloud token is not configured. Skipping login."
          fi
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # pin@v2
        with:
          python-version: '3.8.10'
      - name: Install pre requisites
        run: |
          pip3 install --upgrade pip
          pip3 install ansible fabric3 jsonpickle requests PyYAML firebase_admin
          vagrant plugin install vagrant-vbguest
      - name: Open up network interfaces for VM
        run: |
          sudo mkdir -p /etc/vbox/
          sudo touch /etc/vbox/networks.conf
          sudo sh -c "echo '* 192.168.0.0/16' > /etc/vbox/networks.conf"
          sudo sh -c "echo '* 3001::/64' >> /etc/vbox/networks.conf"
      - name: Prepare the integ test
        run: |
          cd lte/gateway
          export MAGMA_DEV_CPUS=3
          export MAGMA_DEV_MEMORY_MB=9216
          fab bazel_integ_test_pre_build
      - name: Build all services with bazel
        run: |
          cd lte/gateway
          vagrant ssh -c 'cd ~/magma; bazel/scripts/remote_cache_bazelrc_setup.sh "${{ env.CACHE_KEY_MAGMA_DEV }}" "${{ env.REMOTE_DOWNLOAD_OPTIMIZATION }}" "${{ secrets.BAZEL_REMOTE_PASSWORD }}";' magma
          vagrant ssh -c 'sudo sed -i "s@#precedence ::ffff:0:0/96  100@precedence ::ffff:0:0/96  100@" /etc/gai.conf;' magma
          vagrant ssh -c 'cd ~/magma; bazel build --profile=bazel_profile_lte_integ_tests `bazel query "kind(.*_binary, //orc8r/... union //lte/... union //feg/...)"`;' magma
          vagrant ssh -c 'sudo sed -i "s@precedence ::ffff:0:0/96  100@#precedence ::ffff:0:0/96  100@" /etc/gai.conf;' magma
      - name: Setup magma test VM and traffic server VM
        run: |
          cd lte/gateway
          export MAGMA_DEV_CPUS=3
          export MAGMA_DEV_MEMORY_MB=9216
          fab bazel_integ_test_post_build
      - name: Run the integ tests
        run: |
          cd lte/gateway
          vagrant ssh -c 'cd ~/magma; bazel/scripts/remote_cache_bazelrc_setup.sh "${{ env.CACHE_KEY_MAGMA_TEST }}" "${{ env.REMOTE_DOWNLOAD_OPTIMIZATION }}" "${{ secrets.BAZEL_REMOTE_PASSWORD }}";' magma
          # The ssh option '-ttt' is forcing tty allocation, even if ssh has no local tty.
          vagrant ssh -c 'cd ~/magma; bash -c "bazel/scripts/run_integ_tests.sh \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_activation_reject \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_security_algo_eea2_eia2 \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_standalone_act_dflt_ber_ctxt_rej \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service \
            //lte/gateway/python/integ_tests/s1aptests:test_x2_handover_ping_pong \
            //lte/gateway/python/integ_tests/s1aptests:test_mobile_reachability_tmr_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated \
            //lte/gateway/python/integ_tests/s1aptests:test_eps_bearer_context_status_ded_bearer_deact \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_restricted_plmn \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_security_algo_eea1_eia1 \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_bearer_deactivation_invalid_imsi \
            //lte/gateway/python/integ_tests/s1aptests:test_outoforder_attach_complete_ICSR \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_no_ueContext_release_comp \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_act_dflt_ber_ctxt_rej \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_maxbearers_twopdns \
            //lte/gateway/python/integ_tests/s1aptests:test_enb_complete_reset \
            //lte/gateway/python/integ_tests/s1aptests:test_s1setup_failure_incorrect_plmn \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_multiple_secondary_pdn \
            //lte/gateway/python/integ_tests/s1aptests:test_eps_bearer_context_status_def_bearer_deact \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_after_ue_context_release \
            //lte/gateway/python/integ_tests/s1aptests:test_x2_handover \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_abort_after_smc \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_static_ip \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_no_disconnect \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_sctpd_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_ics_timer_expiry_ue_unregistered \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_asr \
            //lte/gateway/python/integ_tests/s1aptests:test_s1setup_failure_incorrect_tac \
            //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_multi_ue_diff_plmn \
            //lte/gateway/python/integ_tests/s1aptests:test_eps_bearer_context_status_multiple_ded_bearer_deact \
            //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_with_dedicated_bearer_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_nw_triggered_delete_last_pdn \
            //lte/gateway/python/integ_tests/s1aptests:test_dedicated_bearer_activation_idle_mode_paging_timer_expiry \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_multi_ue_looped \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_bearer_deactivation_invalid_lbi \
            //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_sctp_shutdown \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service_ue_radio_capability \
            //lte/gateway/python/integ_tests/s1aptests:test_tau_mixed_partial_lists \
            //lte/gateway/python/integ_tests/s1aptests:test_no_attach_complete \
            //lte/gateway/python/integ_tests/s1aptests:test_secondary_pdn_reject_unknown_pdn_type \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_he_policy \
            //lte/gateway/python/integ_tests/s1aptests:test_s1setup_success_secondary_plmn \
            //lte/gateway/python/integ_tests/s1aptests:test_nas_non_delivery_for_auth \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service_with_multi_pdns_and_bearers_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_complete_reset \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_with_dedicated_bearer \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_nw_triggered_delete_secondary_pdn \
            //lte/gateway/python/integ_tests/s1aptests:test_s1_handover \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_mobilityd_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_shutdown_after_smc \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_disconnect_default_pdn \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_ps_service_not_available \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_missing_imsi \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_shutdown_after_auth_req \
            //lte/gateway/python/integ_tests/s1aptests:test_imei_restriction_smc \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_ue_ctxt_release_cmp_delay \
            //lte/gateway/python/integ_tests/s1aptests:test_resync \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_nw_initiated_detach_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_security_algo_eea0_eia0 \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_duplicate_nas_resp_messages \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_ICS_Failure \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_multiple_ip_blocks_mobilityd_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_auth_failure \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_multiple_dedicated \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_shutdown_after_multi_ue_attach \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_without_ips_available \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_combined_eps_imsi \
            //lte/gateway/python/integ_tests/s1aptests:test_no_security_mode_complete \
            //lte/gateway/python/integ_tests/s1aptests:test_gateway_metrics_attach_detach \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_pcscf_address \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_nw_initiated_detach_fail \
            //lte/gateway/python/integ_tests/s1aptests:test_no_auth_response \
            //lte/gateway/python/integ_tests/s1aptests:test_tau_ta_updating_reject \
            //lte/gateway/python/integ_tests/s1aptests:test_idle_mode_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_dedicated_bearer_activation_idle_mode \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_with_dedicated_bearer_looped \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_abort_after_auth_req \
            //lte/gateway/python/integ_tests/s1aptests:test_dedicated_bearer_activation_idle_mode_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_guti_attach_with_zero_mtmsi \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_multi_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_looped \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_bearer_deactivation_invalid_ebi \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_bearer_activation_invalid_imsi \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service_with_multi_pdns_and_bearers_failure \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_with_dedicated_bearer_deactivate \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_activation_timer_expiry \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_security_mode_reject \
            //lte/gateway/python/integ_tests/s1aptests:test_ics_timer_expiry_ue_registered \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_deactivation_timer_expiry \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_esm_information_wrong_apn \
            //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_partial_reset \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_enb_rlf_initial_ue_msg \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_emergency \
            //lte/gateway/python/integ_tests/s1aptests:test_service_info \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_disconnect_dedicated_bearer \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_looped \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_qci_0 \
            //lte/gateway/python/integ_tests/s1aptests:test_3485_timer_for_dedicated_bearer_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_secondary_pdn_reject_multiple_sessions_not_allowed_per_apn \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_mobile_reachability_timer_expiry \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_no_initial_context_resp \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_looped \
            //lte/gateway/python/integ_tests/s1aptests:test_3485_timer_for_default_bearer_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_standalone_pdn_conn_req \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_ipv4v6_pdn_type \
            //lte/gateway/python/integ_tests/s1aptests:test_ics_timer_expiry_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_imei_restriction_no_imeisv_in_smc \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service_with_multi_pdns_and_bearers_looped \
            //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_multi_ue_diff_enbtype \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_invalid_apn \
            //lte/gateway/python/integ_tests/s1aptests:test_tau_periodic_inactive \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_abort_after_identity_req \
            //lte/gateway/python/integ_tests/s1aptests:test_enb_partial_reset_con_dereg \
            //lte/gateway/python/integ_tests/s1aptests:test_identity_timer_3470_expiry \
            //lte/gateway/python/integ_tests/s1aptests:test_enb_partial_reset \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_via_guti \
            //lte/gateway/python/integ_tests/s1aptests:test_tau_ta_updating \
            //lte/gateway/python/integ_tests/s1aptests:test_duplicate_attach \
            //lte/gateway/python/integ_tests/s1aptests:test_different_enb_s1ap_id_same_ue \
            //lte/gateway/python/integ_tests/s1aptests:test_imei_restriction_wildcard_snr \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_service \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_dedicated_bearer_activation_invalid_lbi \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_implicit_detach_timer_expiry \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_ovs \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_emm_status \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_with_pcscf_address \
            //lte/gateway/python/integ_tests/s1aptests:test_implicit_detach_timer_with_mme_restart \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_esm_information \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_secondary_pdn_disconnect_invalid_bearer \
            //lte/gateway/python/integ_tests/s1aptests:test_tau_ta_updating_connected_mode \
            //lte/gateway/python/integ_tests/s1aptests:test_attach_service_with_multi_pdns_and_bearers \
            //lte/gateway/python/integ_tests/s1aptests:test_nas_non_delivery_for_smc \
            //lte/gateway/python/integ_tests/s1aptests:test_nas_non_delivery_for_identity_req \
            //lte/gateway/python/integ_tests/s1aptests:test_sctp_shutdown_after_identity_req"' magma_test -- -ttt
          vagrant ssh -c 'cd ~/magma; cp /var/tmp/test_results/integtest_merged_report/integtests_report.xml .' magma_test -- -ttt
      - name: Publish integ test results
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        if: always()
        with:
          name: test_results
          path: integtests_report.xml
      - name: Publish bazel profile
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        if: always()
        with:
          name: Bazel profile lte integ tests
          path: bazel_profile_lte_integ_tests
      - name: Notify failure to slack
        if: failure() && github.repository_owner == 'magma'
        uses: Ilshidur/action-slack@689ad44a9c9092315abd286d0e3a9a74d31ab78a # pin@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_BAZEL_CI }}
          SLACK_USERNAME: "LTE integ tests bazel"
          SLACK_AVATAR: ":boom:"
        with:
          args: "Bazel LTE integration test failed in run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
